In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
marketing_spends = pd.read_csv('marketing_spend.csv')
orders = pd.read_csv('orders.csv')

In [3]:
marketing_spends

      month       channel  marketing_spend
0   2025-01       organic             0.00
1   2025-01         email           854.05
2   2025-01  social_media          2787.91
3   2025-01    search_ads          3589.30
4   2025-01      referral           282.66
5   2025-02       organic             0.00
6   2025-02         email           892.18
7   2025-02  social_media          2303.16
8   2025-02    search_ads          4256.74
9   2025-02      referral           268.88
10  2025-03       organic             0.00
11  2025-03         email           884.55
12  2025-03  social_media          2828.37
13  2025-03    search_ads          4473.65
14  2025-03      referral           269.40
15  2025-04       organic             0.00
16  2025-04         email           835.91
17  2025-04  social_media          2851.91
18  2025-04    search_ads          3625.51
19  2025-04      referral           275.29
20  2025-05       organic             0.00
21  2025-05         email           909.32
22  2025-05  social_media          2430.98
23  2025-05    search_ads          4577.92
24  2025-05      referral           261.72
25  2025-06       organic             0.00
26  2025-06         email           872.59
27  2025-06  social_media          2788.08
28  2025-06    search_ads          3832.22
29  2025-06      referral           315.66

In [4]:
orders

,order_id,order_date,customer_id,customer_segment,age_group,marketing_channel,device,product_category,unit_price,discount_percent,quantity,final_order_value,delivery_days,customer_rating,returned
0,ORD102024,2025-01-01,CUST02214,returning,18-24,organic,desktop,clothing,37.94,15,1,32.25,6,5,False
1,ORD103143,2025-01-01,CUST02195,new,25-34,social_media,desktop,home,116.92,0,1,116.92,8,4,False
2,ORD100178,2025-01-01,CUST00563,new,35-44,organic,desktop,clothing,63.70,10,3,171.99,4,5,False
3,ORD100175,2025-01-01,CUST00703,new,25-34,social_media,mobile,electronics,141.77,5,2,269.36,11,5,True
4,ORD101491,2025-01-01,CUST01526,new,35-44,social_media,mobile,electronics,108.49,30,2,151.89,9,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5199,ORD102583,2025-06-30,CUST01182,returning,18-24,organic,mobile,home,72.02,10,3,194.45,6,4,False
5200,ORD100580,2025-06-30,CUST02119,returning,35-44,search_ads,mobile,electronics,236.51,10,2,425.72,9,3,False
5201,ORD102655,2025-06-30,CUST01781,new,25-34,email,mobile,beauty,19.66,15,1,16.71,6,5,False
5202,ORD102151,2025-06-30,CUST01592,new,45-54,search_ads,mobile,sports,74.05,0,3,222.15,3,5,False
5203,ORD100434,2025-06-30,CUST00682,new,35-44,search_ads,mobile,electronics,34.02,20,1,27.22,4,5,True

In [5]:
orders['order_date'] = pd.to_datetime(orders['order_date'])
marketing_spends['month'] = pd.to_datetime(marketing_spends['month'], format = '%Y-%m')

In [90]:
month_oreder_velue = orders.groupby(['marketing_channel', orders['order_date'].dt.to_period('M')]).final_order_value.sum().reset_index()
ROI = (month_oreder_velue.final_order_value - marketing_spends.marketing_spend).reset_index()

In [91]:
ROI['channel'] = marketing_spends['channel']
ROI['month'] = marketing_spends['month']
ROI.drop(columns = 'index', inplace = True)
ROI['ROI_percentage'] = (month_oreder_velue.final_order_value - marketing_spends.marketing_spend) / month_oreder_velue.final_order_value * 100

In [92]:
ROI.groupby('channel').ROI_percentage.mean()

channel
email            92.665190
organic         100.000000
referral         97.740745
search_ads       72.507535
social_media     75.017827
Name: ROI_percentage, dtype: float64

самыее выгодные каналы по относительному ROI это email и referral, ихние ROI более чем 90%. убыточных каналов нет.